database:
    host: "localhost"
    port: 5432
    user: "user"
    password: "root"
    name: "orderDB"
stan:
    host: "localhost"
    port: 4222
    —ÅlusterID: "test-cluster"
    clientID: "clientOrder"